# Define the goal
string waypoint  # Specify the waypoint to get associated octomap
string roi_id    # Specify a ROI that you want to observe
string[] models  # NOT AVAILABLE - Specify a list of models you want to observe 
string  mode     # NOT AVAILABLE - Specify the mode of object search (...)
---
# Define the result
uint32 status_code
---
# Define a feedback message
float32 percent_complete
